services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../../backend/api-gateway:/app
    env_file:
      - ../../.env

  redis:
    image: redis:7
    ports:
      - "6379:6379"