services:
  api-gateway:
    build:
      context: ../../backend/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ../../backend/api-gateway:/app
    restart: always

  db:
    image: postgres:16
    container_name: pg-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  auth:
    build:
      context: ../../backend/services/auth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8001:8000"  # Exposed on 8001 externally, runs on 8000 internally
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ../../backend/services/auth:/app
    restart: always

volumes:
  pgdata: